[project]
name = "flaskwebgui"
version = "1.2.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    'psutil~=6.0',
    'uvicorn[standard]'
]
